logging.level.org.nd.template=debug
logging.level.org.springframework=error
logging.level.org.hibernate=error
# db
spring.datasource.url=jdbc:h2:mem:app_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=rootroot
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# jwt
security.jwt.secret-key=eHj3pJnpE45K8YEUkf5peWpPTm5PZQKOtpSRrX5NZOw=
security.jwt.expiration-time-hours=24

